'use client'

import { motion } from 'framer-motion'

const FEATURES = [
  {
    icon: (
      <svg viewBox="0 0 24 24" fill="none" className="w-8 h-8" strokeWidth={1.5}>
        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z" stroke="#10b981" strokeWidth={1.5} />
        <path d="M8 12h4M12 8v8M16 12h-4" stroke="#06b6d4" strokeWidth={1.5} strokeLinecap="round" />
        <circle cx="8" cy="9" r="1.5" fill="#10b981" />
        <circle cx="16" cy="9" r="1.5" fill="#10b981" />
        <circle cx="12" cy="16" r="1.5" fill="#06b6d4" />
      </svg>
    ),
    accent: '#10b981',
    label: 'Graph Intelligence',
    title: 'Network Anomaly Engine',
    description:
      'Detecting Circular Trading using DFS-based Network Analysis on financial transaction graphs. Real-time cycle detection across millions of nodes.',
    tag: 'DFS • Graph Neural Networks',
    metric: '99.7%',
    metricLabel: 'Detection Rate',
  },
  {
    icon: (
      <svg viewBox="0 0 24 24" fill="none" className="w-8 h-8">
        <rect x="3" y="3" width="18" height="18" rx="3" stroke="#06b6d4" strokeWidth={1.5} />
        <path d="M7 17l3-4 3 3 4-6" stroke="#10b981" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" />
        <circle cx="7" cy="17" r="1.5" fill="#06b6d4" />
        <circle cx="10" cy="13" r="1.5" fill="#10b981" />
        <circle cx="13" cy="16" r="1.5" fill="#10b981" />
        <circle cx="17" cy="11" r="1.5" fill="#06b6d4" />
      </svg>
    ),
    accent: '#06b6d4',
    label: 'Behavioral Guard',
    title: 'Velocity Intelligence',
    description:
      'Identifying Smurfing patterns through real-time velocity tracking. Monitors transaction frequency, structuring behavior, and coordination signals.',
    tag: 'ML • Behavioral Biometrics',
    metric: '<50ms',
    metricLabel: 'Alert Latency',
  },
  {
    icon: (
      <svg viewBox="0 0 24 24" fill="none" className="w-8 h-8">
        <path d="M12 3L3 8l9 5 9-5-9-5z" stroke="#10b981" strokeWidth={1.5} strokeLinejoin="round" />
        <path d="M3 16l9 5 9-5" stroke="#06b6d4" strokeWidth={1.5} strokeLinejoin="round" />
        <path d="M3 12l9 5 9-5" stroke="#10b981" strokeWidth={1.5} strokeLinejoin="round" opacity={0.5} />
      </svg>
    ),
    accent: '#a855f7',
    label: 'AI Narrative',
    title: 'Gemini SAR Engine',
    description:
      'Automated SAR reports generated by Gemini 1.5 Flash. Converts raw transaction graphs into compliant, court-ready narratives in seconds.',
    tag: 'Gemini 1.5 Flash • NLP',
    metric: '8 sec',
    metricLabel: 'Report Generation',
  },
]

import { Variants } from 'framer-motion'

const cardVariants: Variants = {
  hidden: { opacity: 0, y: 40 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.15, duration: 0.6, ease: 'easeOut' },
  }),
}

export default function FeatureGrid() {
  return (
    <section className="relative py-24 px-6" id="features">
      {/* Section header */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.7 }}
        className="text-center mb-16"
      >
        <span
          className="inline-block text-xs font-mono font-semibold tracking-widest uppercase px-3 py-1 rounded-full mb-4"
          style={{
            color: '#10b981',
            background: 'rgba(16,185,129,0.1)',
            border: '1px solid rgba(16,185,129,0.3)',
          }}
        >
          Core Capabilities
        </span>
        <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
          The{' '}
          <span
            style={{
              background: 'linear-gradient(90deg, #10b981, #06b6d4)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
            }}
          >
            Power
          </span>{' '}
          Behind TRACR
        </h2>
        <p className="text-slate-400 max-w-xl mx-auto text-lg">
          Three layers of AI-driven defense working in concert to eliminate financial crime.
        </p>
      </motion.div>

      {/* Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto">
        {FEATURES.map((f, i) => (
          <motion.div
            key={f.label}
            custom={i}
            variants={cardVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            whileHover={{ scale: 1.02, y: -4 }}
            className="relative rounded-2xl overflow-hidden group cursor-default"
            style={{
              background: 'rgba(10, 15, 30, 0.7)',
              backdropFilter: 'blur(20px)',
              border: `1px solid rgba(${f.accent === '#10b981' ? '16,185,129' : f.accent === '#06b6d4' ? '6,182,212' : '168,85,247'},0.2)`,
              transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
            }}
          >
            {/* Hover neon border via pseudo-element substitute */}
            <div
              className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl pointer-events-none"
              style={{
                border: `1px solid ${f.accent}`,
                boxShadow: `0 0 30px ${f.accent}40, inset 0 0 30px ${f.accent}08`,
              }}
            />

            {/* Top accent line */}
            <div
              className="absolute top-0 left-0 right-0 h-0.5"
              style={{
                background: `linear-gradient(90deg, transparent, ${f.accent}, transparent)`,
              }}
            />

            <div className="relative p-6">
              {/* Tag */}
              <div className="flex items-center justify-between mb-5">
                <span
                  className="text-xs font-mono tracking-wider uppercase px-2 py-0.5 rounded"
                  style={{ color: f.accent, background: `${f.accent}15` }}
                >
                  {f.label}
                </span>
                <div className="opacity-80">{f.icon}</div>
              </div>

              <h3 className="text-xl font-bold text-white mb-2">{f.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed mb-5">{f.description}</p>

              {/* Tech tags */}
              <div className="flex flex-wrap gap-1.5 mb-5">
                {f.tag.split(' • ').map((t) => (
                  <span
                    key={t}
                    className="text-xs font-mono px-2 py-0.5 rounded"
                    style={{
                      color: f.accent,
                      background: `${f.accent}10`,
                      border: `1px solid ${f.accent}30`,
                    }}
                  >
                    {t}
                  </span>
                ))}
              </div>

              {/* Metric */}
              <div
                className="flex items-center gap-3 pt-4 border-t"
                style={{ borderColor: `${f.accent}20` }}
              >
                <span className="text-2xl font-bold font-mono" style={{ color: f.accent }}>
                  {f.metric}
                </span>
                <span className="text-xs text-slate-500 uppercase tracking-wide">{f.metricLabel}</span>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </section>
  )
}
